export const APP_TITLE = 'Francesco Colamonici'
export const APP_SITE_NAME = 'Francesco Colamonici'
export const APP_DESCRIPTION = 'Francesco Colamonici'
export const APP_URL = 'https://francescocolamonici.it'
export const APP_IMAGE = 'https://francescocolamonici.it/image.jpg'
export const APP_LOGO = 'https://francescocolamonici.it/logo.jpg'
export const APP_FAVICON = 'https://francescocolamonici.it/favicon.ico'

export const APP_TWITTER = 'https://francescocolamonici.it'
export const APP_FACEBOOK = 'https://francescocolamonici.it'
export const APP_GOOGLE = 'https://francescocolamonici.it'
export const APP_YOUTUBE = 'https://francescocolamonici.it'
export const APP_INSTAGRAM = 'https://francescocolamonici.it'
export const APP_PINTEREST = 'https://francescocolamonici.it'
export const APP_LINKEDIN = 'https://francescocolamonici.it'
export const APP_TIKTOK = 'https://francescocolamonici.it'
export const APP_X = 'https://francescocolamonici.it'
export const APP_SNAPCHAT = 'https://francescocolamonici.it'
